<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shu Fai Cheung">
<meta name="dcterms.date" content="2023-07-01">

<title>Proper Standardization in Moderated Regression Using std_selected_boot() – Blogonresearch</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d166b450ba5a8e9f7a0ab969bf6592c1.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-96e55dd22b6614b1fe21a4f5e55415bc.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-48e6a02e4ba072bb7983431fac7d6efa.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../blongonresearch_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blogonresearch</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-r-packages-and-other-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">R Packages and Other Tools</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-r-packages-and-other-tools">    
        <li>
    <a class="dropdown-item" href="https://sfcheung.github.io/manymome/">
 <span class="dropdown-text">manymome: Mediation, moderation, and moderated mediation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://sfcheung.github.io/semhelpinghands/">
 <span class="dropdown-text">semhelpinghands: Some helpers for doing SEM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://sfcheung.github.io/semptools/">
 <span class="dropdown-text">semptools: Drawing models from lavaan</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/sfcheung/semfindr">
 <span class="dropdown-text">semfindr: Influential cases in SEM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://sfcheung.github.io/stdmod/">
 <span class="dropdown-text">stdmod: Standardized moderation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://sfcheung.github.io/semlbci/">
 <span class="dropdown-text">semlbci: Likelihood-Based Confidence Interval in SEM</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://osf.io/dbm5c/">
 <span class="dropdown-text">FINDOUT: Influential cases in AMOS</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/sfcheung/diybootstat">
 <span class="dropdown-text">DIY Bootstrapping in SPSS</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/blogonresearch"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/blogonresearch"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Proper Standardization in Moderated Regression Using std_selected_boot()</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">regression</div>
                <div class="quarto-category">moderation</div>
                <div class="quarto-category">stdmod</div>
                <div class="quarto-category">standardized</div>
                <div class="quarto-category">bootstrapping</div>
                <div class="quarto-category">confidence-intervals</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Shu Fai Cheung </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 1, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>This post shows one simple way to get correctly standardized regression coefficients in multiple linear regression with a moderator, with appropriate confidence intervals, using <code>std_selected_boot()</code> from the <a href="https://sfcheung.github.io/stdmod/"><code>stdmod</code></a> package.</p>
<p>(<em>Note</em>: This post and some related posts, e.g., <a href="https://blogonresearch.github.io/posts/std_dummy/">this one on categorical variables</a>, have sections that are identical or highly similar. This is <em>intentional</em>, to make each article self-contained. Readers do not need to refer to other articles to understand the points.)</p>
<section id="betas" class="level1">
<h1>“Betas”</h1>
<p>It is common in my area, psychology, to report standardized coefficients, the so-called “betas,” when reporting the results of multiple regression or related methods. It is so common that some programs have the “betas” reported by default, alongside the unstandardized coefficients (the “Bs”).</p>
<p>However, when a regression model has a moderator and hence a product term, the common practice, standardizing all variables, including the product term, will lead to “betas” that is difficult to interpret.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A Standardized Product Is Not A Product of Standardized Variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>That is, the standardized <span class="math inline">\(x \times w\)</span> is not <span class="math inline">\(\textrm{standardized } x \times \textrm{standardized } w\)</span>. The value of the former is no longer a measure of the moderation effect.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
</div>
<p>This point is not new. <span class="citation" data-cites="friedrich_defense_1982">Friedrich (<a href="#ref-friedrich_defense_1982" role="doc-biblioref">1982</a>)</span> has discussed this a long time ago, and <span class="citation" data-cites="aiken_multiple_1991">Aiken &amp; West (<a href="#ref-aiken_multiple_1991" role="doc-biblioref">1991</a>)</span> have also explored this in details.</p>
<p>Unfortunately, reporting the “beta” of the product term computed this way is quite common (including in my own work).</p>
<p>The solutions are simple:</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Standardize The Components
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the product term <span class="math inline">\(x \times w\)</span>, standardize <span class="math inline">\(x\)</span> (<span class="math inline">\(z_x\)</span>) and <span class="math inline">\(w\)</span> (<span class="math inline">\(z_w\)</span>), and compute the product of them, <span class="math inline">\(z_x \times z_w\)</span>.</p>
</div>
</div>
<p>However, common statistical programs standardize <em>all</em> variables. To do standardization <em>right</em> in moderated regression, we need to <em>manually</em> do the standardization and compute the product term, <em>twice</em>.</p>
<p>The function <code>std_selected_boot()</code> from the R package <code>stdmod</code>, which I and my collaborators developed for moderated regression <span class="citation" data-cites="cheung_improving_2022">(<a href="#ref-cheung_improving_2022" role="doc-biblioref">Cheung et al., 2022</a>)</span>, can do the standardization as presented in <span class="citation" data-cites="aiken_multiple_1991">Aiken &amp; West (<a href="#ref-aiken_multiple_1991" role="doc-biblioref">1991</a>)</span> and <span class="citation" data-cites="friedrich_defense_1982">Friedrich (<a href="#ref-friedrich_defense_1982" role="doc-biblioref">1982</a>)</span>, without any drastic changes to the common workflow.</p>
</section>
<section id="how-to-use-std_selected_boot" class="level1">
<h1>How to Use <code>std_selected_boot()</code></h1>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Workflow
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Fit a regression model by <code>lm()</code> as usual.</p></li>
<li><p>Pass the output to <code>std_selected_boot()</code> and select variables to be standardized.</p></li>
</ol>
</div>
</div>
<p>It was designed to let users have full control on which variables to standardize (see this <a href="https://sfcheung.github.io/stdmod/articles/std_selected.html">article</a> on how). It has one additional feature:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What It Won’t Do (Correctly)
</div>
</div>
<div class="callout-body-container callout-body">
<p>If a model has product terms, they will be formed <em>after</em> the component terms are standardized.</p>
</div>
</div>
<section id="example" class="level2">
<h2 class="anchored" data-anchor-id="example">Example</h2>
<section id="do-regression-as-usual" class="level3">
<h3 class="anchored" data-anchor-id="do-regression-as-usual">Do Regression As Usual</h3>
<p>Suppose this is the data set:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code for generating data</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">342532</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>control1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">5</span>, <span class="dv">1</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>control2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">20</span>, <span class="dv">5</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">10</span>, <span class="dv">4</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="dv">10</span>, <span class="dv">2</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> control1 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> control2 <span class="sc">+</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>     (<span class="dv">3</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> (w <span class="sc">-</span> <span class="dv">10</span>)) <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="dv">30</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(control1, control2, x, w, y)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(dat, <span class="st">"dat.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>This is the <a href="dat.csv">data file</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  control1 control2         x         w         y
1 5.025877 22.32080  9.521779 11.049711 131.15905
2 6.200119 17.04644 11.912240 10.860813 102.01347
3 4.992346 27.28403  9.845949 10.515219  77.86161
4 4.979231 12.85510  6.512449 13.635488  89.54024
5 7.020257 15.48984  5.734798  9.846383  66.94897
6 3.969682 24.61428  3.329810 10.221247  38.20317</code></pre>
</div>
</div>
<p>The variable <code>x</code> is the predictor, <code>w</code> the moderator. The dataset also has two control variables, <code>control1</code> and <code>control2</code>. The outcome variable is <code>y</code>.</p>
<p>This is the regression model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lm_out <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> control1 <span class="sc">+</span> control2 <span class="sc">+</span> x<span class="sc">*</span>w, dat)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ control1 + control2 + x * w, data = dat)

Residuals:
    Min      1Q  Median      3Q     Max 
-86.895 -18.374  -0.556  19.255  70.971 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  40.8781    29.5919   1.381 0.168746    
control1     -2.2750     2.1314  -1.067 0.287129    
control2      1.0053     0.3821   2.631 0.009191 ** 
x            -4.6922     2.3479  -1.998 0.047060 *  
w             0.3635     2.4452   0.149 0.881986    
x:w           0.7780     0.2287   3.402 0.000811 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 28.34 on 194 degrees of freedom
Multiple R-squared:  0.3587,    Adjusted R-squared:  0.3422 
F-statistic:  21.7 on 5 and 194 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The moderation effect is significant.</p>
<ul>
<li><p>If <code>w</code> increases by one unit, the effect of <code>x</code> increases by 0.778.</p></li>
<li><p>If <code>w</code> is equal to zero, the effect of <code>x</code> is -4.692, and significant.</p></li>
</ul>
</section>
<section id="do-standardization-right" class="level3">
<h3 class="anchored" data-anchor-id="do-standardization-right">Do Standardization Right</h3>
<p>Install <code>stdmod</code> and load it:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stdmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we want to standardize all variables except for the product term, <em>and</em> compute the product term as the product of the <em>standardized</em> variables, we just pass the output to <code>std_selected_boot()</code>, and set <code>to_standardize</code> to <code>~ .</code>. The right-hand side of <code>~</code> denotes the variables to be standardized. If set to <code>.</code>, then all numeric variables, including the outcome variable (<code>y</code>), will be standardized.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>But this is not just about the coefficient. There is one issue with standardization: <strong>confidence intervals</strong>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Beware of the <em>t</em>-based SE and CI
</div>
</div>
<div class="callout-body-container callout-body">
<p>If a variable is standardized, the usual <em>t</em>-based standard errors and confidence intervals of the coefficients that involve it <em>may</em> be biased.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
</div>
<p>This is because (a) they do not take into account the sampling variation of the standard deviations used in standardization <span class="citation" data-cites="yuan_biases_2011">(<a href="#ref-yuan_biases_2011" role="doc-biblioref">Yuan &amp; Chan, 2011</a>)</span>, and (b) the coefficients with standardization, the “betas”, are not normally distributed (though may be close to). Many statistical programs do not report the confidence intervals for “betas,” for a good reason.</p>
<p>The case of moderated regression is more complicated because, as shown in <span class="citation" data-cites="cheung_improving_2022">Cheung et al. (<a href="#ref-cheung_improving_2022" role="doc-biblioref">2022</a>)</span>, the correctly standardized product term involves the standard deviations of <em>three</em> variables, not two.</p>
<p>This is why <code>std_selected_boot()</code> enables nonparametric bootstrapping percentile confidence intervals <em>by default</em>, just in case the bias is large.</p>
<p>To have stable and reproducible confidence intervals, call <code>set.seed()</code> before calling <code>std_selected_boot()</code> and set <code>nboot</code> to the desired number of bootstrap samples (at least 2000 but 5000 or more is recommended):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">645321</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>lm_out_std <span class="ot">&lt;-</span> <span class="fu">std_selected_boot</span>(lm_out,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">to_standardize =</span> <span class="sc">~</span> .,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">nboot =</span> <span class="dv">5000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Call <code>summary()</code> as usual:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_out_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call to std_selected_boot():
std_selected_boot(lm_out = lm_out, to_standardize = ~., nboot = 5000)

Selected variable(s) are centered by mean and/or scaled by SD
- Variable(s) centered: y control1 control2 x w
- Variable(s) scaled: y control1 control2 x w

         centered_by  scaled_by                            Note
y          83.477789 34.9370599 Standardized (mean = 0, SD = 1)
control1    5.060548  0.9562693 Standardized (mean = 0, SD = 1)
control2   19.625484  5.3780625 Standardized (mean = 0, SD = 1)
x           9.844108  4.3166239 Standardized (mean = 0, SD = 1)
w          10.132063  2.0474763 Standardized (mean = 0, SD = 1)

Note:
- Categorical variables will not be centered or scaled even if
  requested.
- Nonparametric bootstrapping 95% confidence intervals computed.
- The number of bootstrap samples is 5000.

Call:
lm(formula = y ~ control1 + control2 + x * w, data = dat_mod)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.48720 -0.52591 -0.01591  0.55113  2.03139 

Coefficients:
            Estimate CI Lower CI Upper Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.0201  -0.0059   0.0522     0.0577  0.3492 0.727347    
control1     -0.0623  -0.1528   0.0361     0.0583 -1.0674 0.287129    
control2      0.1548   0.0454   0.2650     0.0588  2.6312 0.009191 ** 
x             0.3941   0.2776   0.5028     0.0596  6.6154  &lt; 0.001 ***
w             0.4701   0.3586   0.5735     0.0580  8.1079  &lt; 0.001 ***
x:w           0.1968   0.0981   0.2893     0.0578  3.4023  &lt; 0.001 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.811 on 194 degrees of freedom

R-squared                : 0.3587
Adjusted R-squared       : 0.3422
ANOVA test of R-squared  : F(5, 194) = 21.7047, p &lt; 0.001

= Test the highest order term =
The highest order term             : x:w
R-squared increase adding this term: 0.0383
F test of R-squared increase       : F(1, 194) = 11.5759, p &lt; 0.001

Note:
- Estimates and their statistics are based on the data after
  mean-centering, scaling, or standardization.
- [CI Lower, CI Upper] are bootstrap percentile confidence intervals.
- Std. Error are not bootstrap SEs.</code></pre>
</div>
</div>
<p>The output has one additional section:</p>
<ul>
<li>Variables that are standardized<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, and variables that are not transformed.</li>
</ul>
<p>As shown in the first section, <code>x</code> and <code>w</code> are standardized. <code>x:w</code> is not on the list. It is because <code>x:w</code> is not standardized. It should not be, as explained above.</p>
<p>The other sections are similar to those for a usual multiple regression. Note that the column <code>Estimate</code> is intentionally <em>not</em> labelled as <code>Beta</code> because it is possible that only some variables are standardized. Labelling it as <code>Beta</code>, though common, is misleading.</p>
</section>
<section id="interpret-the-output" class="level3">
<h3 class="anchored" data-anchor-id="interpret-the-output">Interpret The Output</h3>
<p>The coefficient of the product term <code>x:w</code> is 0.197. That is, for each one <em>SD</em> increase of <code>w</code>, the <em>standardized</em> effect of <code>x</code> on <code>y</code> ( the “beta” of <code>x</code> on <code>y</code>) increases by 0.197.</p>
<p>My collaborator and I proposed to call the moderation effect with <code>x</code>, <code>w</code>, and <code>y</code> standardized, <code>x:w</code> in the example, the <em>standardized moderation effect</em> <span class="citation" data-cites="cheung_improving_2022">(<a href="#ref-cheung_improving_2022" role="doc-biblioref">Cheung et al., 2022</a>)</span>. When variables are standardized as proposed by <span class="citation" data-cites="friedrich_defense_1982">Friedrich (<a href="#ref-friedrich_defense_1982" role="doc-biblioref">1982</a>)</span>, the coefficients can be interpreted as usual in moderated regression, with all variables on the standardized metric.</p>
<p>The coefficient of <code>x</code> is 0.394. This is the <em>standardized</em> effect (the “beta”) of <code>x</code> when <code>w</code> in this model is equal to zero. Because <code>w</code> is standardized, this is equivalent to say that this is the standardized effect of <code>x</code> when <code>w</code> is equal to its mean because the mean of a standardized variable is zero.</p>
</section>
<section id="conditional-effect" class="level3">
<h3 class="anchored" data-anchor-id="conditional-effect">Conditional Effect</h3>
<p>The function <code>cond_effect_boot()</code> from <code>stdmod</code> can be used to compute the conditional effects. Just pass the output of <code>lm()</code> or <code>std_selected_boot()</code> to it.</p>
<p>When the variables are standardized, <code>cond_effect_boot()</code> can be used to compute the <em>standardized</em> conditional effects, with nonparametric bootstrap confidence intervals. Just set <code>nboot</code> to the desired number of bootstrap samples. To ensure that the same <code>nboot</code> bootstrap samples are drawn, set the seed to the number used in <code>std_seleted_boot()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">645321</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cond_std <span class="ot">&lt;-</span> <span class="fu">cond_effect_boot</span>(lm_out_std,</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">x =</span> <span class="st">"x"</span>,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">w =</span> <span class="st">"w"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">nboot =</span> <span class="dv">5000</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>cond_std</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The effects of x on y, conditional on w:

  Level      w x Effect CI Lower CI Upper  S.E.     t     p Sig
   High  1.000    0.591    0.429    0.737 0.085 6.982 0.000 ***
 Medium  0.000    0.394    0.278    0.503 0.060 6.615 0.000 ***
    Low -1.000    0.197    0.051    0.340 0.081 2.424 0.016 *  

[CI Lower, CI Upper] shows the 95% nonparametric bootstrap confidence
interval(s) (based on 5000 bootstrap samples).


The regression model:

    y ~ control1 + control2 + x * w

Interpreting the levels of w:

  Level      w % Below From Mean (in SD)
   High  1.000   81.50              1.00
 Medium  0.000   51.00              0.00
    Low -1.000   15.00             -1.00

- % Below: The percent of cases equal to or less than a level.
- From Mean (in SD): Distance of a level from the mean, in standard
  deviation (+ve above, -ve below).

Note:

- The variable(s) y, x, w is/are standardized.
- The conditional effects are the standardized effects of x on y.</code></pre>
</div>
</div>
<p>As shown above, the effect of <code>x</code> is positive and significant when <code>w</code> ranges from one SD below mean to one SD above mean. The <em>standardized</em> effect of <code>x</code> on <code>y</code> when <code>w</code> is one SD above mean is 0.591.</p>
</section>
</section>
</section>
<section id="why-the-usual-practice-is-problematic" class="level1">
<h1>Why The Usual Practice Is Problematic</h1>
<section id="standardize-the-product-term" class="level2">
<h2 class="anchored" data-anchor-id="standardize-the-product-term">Standardize the Product Term</h2>
<p>Assume that we standardize <em>all</em> variables, including the product term, as in some statistical program. To simulate this, let’s manually create the product term, standardize all variables, including the product term, and do regression:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>x_w <span class="ot">&lt;-</span> dat<span class="sc">$</span>x <span class="sc">*</span> dat<span class="sc">$</span>w</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>dat_std <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(dat))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     control1   control2             x           w          y        x_w
1 -0.03625650  0.5011678 -0.0746715806  0.44818493  1.3647761  0.1360233
2  1.19168346 -0.4795487  0.4791086834  0.35592570  0.5305451  0.6515372
3 -0.07132155  1.4240348  0.0004264965  0.18713570 -0.1607514  0.1001691
4 -0.08503578 -1.2588894 -0.7718205413  1.71109398  0.1735248 -0.2141245
5  2.04932709 -0.7689844 -0.9519731607 -0.13952791 -0.4731027 -0.9039326
6 -1.14075236  0.9276200 -1.5091188133  0.04355764 -1.2958909 -1.3825065</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">describe</span>(dat_std, <span class="at">range =</span> <span class="cn">FALSE</span>, <span class="at">skew =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>         vars   n mean sd   se
control1    1 200    0  1 0.07
control2    2 200    0  1 0.07
x           3 200    0  1 0.07
w           4 200    0  1 0.07
y           5 200    0  1 0.07
x_w         6 200    0  1 0.07</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lm_out_std_wrong <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> control1 <span class="sc">+</span> control2 <span class="sc">+</span> x <span class="sc">+</span> w <span class="sc">+</span> x_w, dat_std)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The following results are what found in common statistical programs that standardize all variables, including the product term, to yield the “betas”:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">printCoefmat</span>(<span class="fu">summary</span>(lm_out_std_wrong)<span class="sc">$</span>coefficients,</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">zap.ind =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">P.values =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.000000   0.057350  0.0000  1.00000    
control1    -0.062270   0.058339 -1.0674  0.28713    
control2     0.154750   0.058813  2.6312  0.00919 ** 
x           -0.579740   0.290091 -1.9985  0.04706 *  
w            0.021300   0.143300  0.1486  0.88199    
x_w          1.043740   0.306771  3.4023  0.00081 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Let us compare the results.</p>
<section id="p-values" class="level3">
<h3 class="anchored" data-anchor-id="p-values"><em>p</em>-values</h3>
<p>Some <em>p</em>-values are different, which is expected:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>coef_std <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_out_std)<span class="sc">$</span>coefficients</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>coef_std_wrong <span class="ot">&lt;-</span> <span class="fu">summary</span>(lm_out_std_wrong)<span class="sc">$</span>coefficients</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="st">`</span><span class="at">p-value (Std Correct)</span><span class="st">`</span> <span class="ot">=</span> coef_std[, <span class="st">"Pr(&gt;|t|)"</span>],</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">p-value (Std All)</span><span class="st">`</span> <span class="ot">=</span> coef_std_wrong[, <span class="st">"Pr(&gt;|t|)"</span>]), <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            p-value (Std Correct) p-value (Std All)
(Intercept)               0.72735           1.00000
control1                  0.28713           0.28713
control2                  0.00919           0.00919
x                         0.00000           0.04706
w                         0.00000           0.88199
x:w                       0.00081           0.00081</code></pre>
</div>
</div>
<p>The <em>p</em>-values of <code>x:w</code> are the same, which is expected <span class="citation" data-cites="aiken_multiple_1991">(see <a href="#ref-aiken_multiple_1991" role="doc-biblioref">Aiken &amp; West, 1991</a>)</span>.</p>
<p>However, the <em>p</em>-values of <code>x</code> and <code>w</code> are very different. This is not just because they are effects of <code>x</code> and <code>w</code> conditional on other values. They actually are <em>not</em> conditional effects as we usually understood, explained in the next section.</p>
</section>
<section id="coefficient-estimates" class="level3">
<h3 class="anchored" data-anchor-id="coefficient-estimates">Coefficient Estimates</h3>
<p>Let us compare the coefficients:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cbind</span>(<span class="st">`</span><span class="at">Estimate (Std Correct)</span><span class="st">`</span> <span class="ot">=</span> coef_std[, <span class="st">"Estimate"</span>],</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>            <span class="st">`</span><span class="at">Estimate (Std All)</span><span class="st">`</span> <span class="ot">=</span> coef_std_wrong[, <span class="st">"Estimate"</span>]), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            Estimate (Std Correct) Estimate (Std All)
(Intercept)                  0.020              0.000
control1                    -0.062             -0.062
control2                     0.155              0.155
x                            0.394             -0.580
w                            0.470              0.021
x:w                          0.197              1.044</code></pre>
</div>
</div>
<p>The coefficients of <code>x</code>, <code>w</code>, and <code>x:w</code> have very different values between the correct standardized solution and the standardized solution with product term standardized.</p>
<p>Two points of note for the second column, the solution with the product term itself standardized:</p>
<ol type="1">
<li><p>The coefficient of <code>x:w</code> , when it is standardized (called <code>x_w</code>), is not a product term. The value 1.044 is <em>not</em> the increase of effect of <code>x</code> when <code>w</code> increases by one SD, nor by one unit.</p></li>
<li><p>The coefficient of <code>x</code> is <em>not</em> the usual conditional effect. Mathematically, it is the standardized effect of <code>x</code> when <code>w</code> is equal to “some value”. However, what is this value? This is not easy to determine because <code>x_w</code> is not a product term. The coefficient of <code>w</code> has the same problem.</p></li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Standardizing the Product Term Make Interpretation Difficult
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The coefficient of the product term is no longer the moderation effect (except in some very special cases).</li>
<li>The coefficients of the component terms, the focal variable and the moderator, are no longer the conditional effects of values easily deducible from the results.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="use-t-statistics-confidence-intervals" class="level2">
<h2 class="anchored" data-anchor-id="use-t-statistics-confidence-intervals">Use <em>t</em> Statistics Confidence Intervals</h2>
<p>Some programs gives confidence intervals of “betas” using <em>t</em> statistics. That is, standardize variables, do regression, and form the confidence intervals, as if the standardized variables were the original data.</p>
<p>Let us compare the bootstrap confidence intervals with the usual OLS confidence intervals based on the <em>t</em>-statistics.</p>
<p>For the output of <code>std_selected_boot()</code>, we can request the <em>t</em>-based confidence intervals by setting <code>type</code> to <code>"lm"</code> when calling <code>confint()</code>, the function commonly used to form confidence intervals:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OLS confidence intervals</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">confint</span>(lm_out_std, <span class="at">type =</span> <span class="st">"lm"</span>), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept) -0.094  0.134
control1    -0.177  0.053
control2     0.039  0.271
x            0.277  0.512
w            0.356  0.584
x:w          0.083  0.311</code></pre>
</div>
</div>
<p>Without setting <code>type</code>, the nonparametric bootstrap confidence intervals are returned (if available):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bootstrap Confidence Intervals</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">confint</span>(lm_out_std), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             2.5 % 97.5 %
(Intercept) -0.006  0.052
control1    -0.153  0.036
control2     0.045  0.265
x            0.278  0.503
w            0.359  0.574
x:w          0.098  0.289</code></pre>
</div>
</div>
<p>As shown above, the confidence intervals of <code>x</code>, <code>w</code>, and <code>x:w</code> by the two methods are close to each other. However, the bootstrap confidence intervals tend to be narrower than the <em>t</em>-based confidence intervals.</p>
<p>We can compare the widths of the confidence intervals by examining their ratios (<code>ratio</code> = <code>CI_Width_t</code> / <code>CI_Width_boot</code>):</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>ci_t <span class="ot">&lt;-</span> <span class="fu">confint</span>(lm_out_std, <span class="at">type =</span> <span class="st">"lm"</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>ci_b <span class="ot">&lt;-</span> <span class="fu">confint</span>(lm_out_std)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>width_t <span class="ot">&lt;-</span> ci_t[, <span class="dv">2</span>] <span class="sc">-</span> ci_t[, <span class="dv">1</span>]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>width_b <span class="ot">&lt;-</span> ci_b[, <span class="dv">2</span>] <span class="sc">-</span> ci_b[, <span class="dv">1</span>]</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>ci_compare <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">CI_Width_t =</span> width_t,</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">CI_Width_boot =</span> width_b)</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>ci_compare<span class="sc">$</span>ratio <span class="ot">&lt;-</span> ci_compare[, <span class="dv">1</span>] <span class="sc">/</span> ci_compare[, <span class="dv">2</span>]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ci_compare, <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>            CI_Width_t CI_Width_boot ratio
(Intercept)      0.227         0.058 3.918
control1         0.230         0.189 1.218
control2         0.232         0.220 1.056
x                0.235         0.225 1.044
w                0.229         0.215 1.064
x:w              0.228         0.191 1.193</code></pre>
</div>
</div>
<p>The <em>t</em>-based confidence interval of the product term, the standardized moderation effect, is nearly 19.3% wider than the bootstrap confidence interval.</p>
</section>
</section>
<section id="final-remarks" class="level1">
<h1>Final Remarks</h1>
<p>What <code>std_selected_boot()</code> does can be implemented in R code by researchers using base R packages only. The function was developed to make it easier for researchers to do standardization right in moderated regression, without adopting the all-or-none approach.</p>
<p>More information on <code>std_selected_boot()</code> can be found from its <a href="https://sfcheung.github.io/stdmod/reference/std_selected.html">help page</a>.</p>
</section>
<section id="other-resources" class="level1">
<h1>Other Resources</h1>
<p>There are programs that advocate the correct way to do standardization in moderated regression. For example, users are recommended to standardize variables before using them to do moderated regression. Done this way, they yield correct point estimates for standardized solution as <code>std_selected_boot()</code> does.</p>
<p>However, I am not aware of program that do the bootstrapping correctly when forming the bootstrapping confidence interval for the correctly standardized solution. It is because <em>both</em> the multiple regression <em>and</em> standardization need to be done in <em>each</em> bootstrap sample. If standardization is done only once, before doing bootstrapping, even though the point estimates are correct, the bootstrap confidence intervals are not.</p>
</section>
<section id="revision-history-and-issues" class="level1">
<h1>Revision History and Issues</h1>
<p>The revision history of this post can be find in the <a href="https://github.com/blogonresearch/blogonresearch.github.io/commits/main/posts/std_mod/index.qmd">GitHub history of the source file</a>.</p>
<p>For issues on this post, such as corrections and mistakes, please <a href="https://github.com/blogonresearch/blogonresearch.github.io/issues">open an issue</a> for the GitHub repository for this blog. Thanks.</p>



</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-aiken_multiple_1991" class="csl-entry" role="listitem">
Aiken, L. S., &amp; West, S. G. (1991). <em>Multiple regression: <span>Testing</span> and interpreting interactions</em>. SAGE Publication.
</div>
<div id="ref-cheung_improving_2022" class="csl-entry" role="listitem">
Cheung, S. F., Cheung, S.-H., Lau, E. Y. Y., Hui, C. H., &amp; Vong, W. N. (2022). Improving an old way to measure moderation effect in standardized units. <em>Health Psychology</em>, <em>41</em>(7), 502–505. <a href="https://doi.org/10.1037/hea0001188">https://doi.org/10.1037/hea0001188</a>
</div>
<div id="ref-friedrich_defense_1982" class="csl-entry" role="listitem">
Friedrich, R. J. (1982). In defense of multiplicative terms in multiple regression equations. <em>American Journal of Political Science</em>, <em>26</em>(4), 797–833. <a href="https://doi.org/10.2307/2110973">https://doi.org/10.2307/2110973</a>
</div>
<div id="ref-yuan_biases_2011" class="csl-entry" role="listitem">
Yuan, K.-H., &amp; Chan, W. (2011). Biases and standard errors of standardized regression coefficients. <em>Psychometrika</em>, <em>76</em>(4), 670–690. <a href="https://doi.org/10.1007/s11336-011-9224-6">https://doi.org/10.1007/s11336-011-9224-6</a>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Standardized <span class="math inline">\(x \times w\)</span> can be close to <span class="math inline">\(\textrm{standardized } x \times \textrm{standardized } w\)</span>, but only in some very specific situations, as shown in <span class="citation" data-cites="cheung_improving_2022">Cheung et al. (<a href="#ref-cheung_improving_2022" role="doc-biblioref">2022</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Suppose we only want to standardize <code>x</code> and <code>y</code>, because <code>w</code> is on a meaningful unit, we can set <code>to_standardize</code> to <code>~ x + y</code>. Order does not matter.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Note that there are indeed cases in which they are still unbiased, and cases in which the biases are negligible. See <span class="citation" data-cites="yuan_biases_2011">Yuan &amp; Chan (<a href="#ref-yuan_biases_2011" role="doc-biblioref">2011</a>)</span> for a detailed discussion.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><code>std_selected_boot()</code> allows users to do only mean-centering or scaling by standard deviation. Meaning-centering and than scaling by standard deviation is equivalent to standardization.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/blogonresearch\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"></a><br>This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>