publishDir: "../docs"
baseurl: https://blogonresearch.github.io/
ignoreFiles:
- \\.Rmd$
- \\.Rmarkdown$
- _cache$
languageCode: en-us
theme: hugo-theme-hello-friend
paginate: 5
params:
  rssFullText: true
  contentTypeName: post
  defaultTheme: light
  showMenuItems: 4
  showReadingTime: no
  shareButtons:
    size: small
    icon: solid
    networks:
      - facebook
      - twitter
      - linkedin
      - whatsapp
      - telegram
      - email
languages:
  en:
    copyright: ''
    dateFormatList: '2006-01-02'
    dateFormatSingle: '2006-01-02'
    keywords: ''
    menu:
      main:
        - identifier: about
          name: About
          url: /about
        # - identifier: showcase
        #   name: Showcase
        #   url: /showcase
        - identifier: attwitter
          name: On Twitter
          url: https://twitter.com/blogonresearch
        - identifier: rbloggers
          name: R-Bloggers
          url: https://www.r-bloggers.com/
    menuMore: Show more
    minuteReadingTime: min read
    newerPosts: Newer posts
    olderPosts: Older posts
    params:
      logo:
        logoHomeLink: /
        logoText: Blogonresearch
        # path: "img/blongonresearch_logo.png"
        # alt: "Blogonresearch"
    readMore: Read more
    readOtherPosts: Read other posts
    subtitle: A blog on ... research
    title: Blogonresearch
    writtenBy:

markup:
  highlight:
    codeFences: true
    anchorLineNos: false
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true
